# Run executable for every day
run-all:
  for directory in `ls -d day*`; \
    do just run $directory; \
  done

# Run tests for every day
test-all +flags="-count=1":
  for directory in `ls -d day*`; \
    do just test $directory {{flags}}; \
  done

# Run exectutable for specified day
run day:
  go run {{day}}/{{day}}.go

# Run test for specified day
test day +flags="-count=1":
  go test {{flags}} ./{{day}}
